name: MCS
main: me.lester.t.MCS
version: 1.0
commands:
  creative:
    description: Changes GameMode to Creative.
  survival:
    description: Changes GameMode to Survival.
  smite:
    description: Changes player GameMode to survival and smites that specific player.